# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Juan Pablo Aviña Cuevas
title: Senior Network System Computer Enginner
email: juanpabloavinacuevas360@gmail.com
website: www.github.com/fastdemon29/resume-theme
phone number: 3328168295
address: Eulogio Parra 424, int.2

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: fastdemon29
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: (https://www.instagram.com/juan.pablo_29/) juan.pablo_29
linkedin_username: (https://www.linkedin.com/in/juan-pablo-avi%C3%B1a-cuevas-90432b251/) juan pablo aviña cuevas
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: (https://www.youtube.com/channel/UCJAQCB0keCBoSUNrwBAGZ3g) juan pablo aviña
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/Juanpa.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Juan Pablo and I'm a senior network system administrator. As well as administrating systems I also have experience making software and web apps. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>Python</mark> and <mark>Eating Pizza</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/fastdemon29
        # link_text: Project Website
        additional_links:
          - title: fastdemon29/modern-resume-theme
            icon: fab fa-github
            url: github.com/fastdemon29/modern-resume-theme
          # - title:  Github page for project (eg. fastdemon29/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. fastdemon29.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Bimbo Company
        link: bimbocompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Computer
        caption: February 2024 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Bimbo Company is no exception. It is based on storing data that contains all the information from all the areas that are part of the company. Likewise, in the creation of an application for the promotion of products so that they are more efficient and more recognized by the general public.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: CUCEI University
        caption: 2020 - 2024
        sub_title: BSc Computer Science
        quote: >
          Established in 1790, CUCEI is the oldest higher education institution in the Guadalajara, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the Jalisco but also the Mexico.
        description: | # this will include new lines to allow paragraphs
          During my time at CUCEI. I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a I spent a lot of my free time as a practicing programs and courses with my colleagues and friends to strengthen knowledge and prepare for what is coming in the future.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Play soccer or other sports with friends
      - video game
      - [be like peter parker](https://www.youtube.com/watch?v=QCNinrT3u3c)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
